// 由 assets-qqpet/sheets/sheets.json 生成：QQ 企鹅原版素材（Flash SWF -> PNG 帧 -> WebP 精灵图）
// 每张图 COLS 列，格子 140x140，原始帧率 12 fps，帧序从左到右、从上到下。
export const CELL = [140, 140];
export const COLS = 10;
export const SHEETS = {
  Clean: { frames: 238, rows: 24, file: "Clean.webp" },
  Clean2: { frames: 214, rows: 22, file: "Clean2.webp" },
  Cure: { frames: 118, rows: 12, file: "Cure.webp" },
  Eat: { frames: 146, rows: 15, file: "Eat.webp" },
  Eat2: { frames: 120, rows: 12, file: "Eat2.webp" },
  EggAppear: { frames: 62, rows: 7, file: "EggAppear.webp" },
  EggStand: { frames: 101, rows: 11, file: "EggStand.webp" },
  Enter: { frames: 108, rows: 11, file: "Enter.webp" },
  Exit: { frames: 99, rows: 10, file: "Exit.webp" },
  GGEat: { frames: 146, rows: 15, file: "GGEat.webp" },
  GGHappy: { frames: 283, rows: 29, file: "GGHappy.webp" },
  GGIdle: { frames: 97, rows: 10, file: "GGIdle.webp" },
  Happy: { frames: 180, rows: 18, file: "Happy.webp" },
  Happy2: { frames: 154, rows: 16, file: "Happy2.webp" },
  HappyHi: { frames: 40, rows: 4, file: "HappyHi.webp" },
  Hi1: { frames: 66, rows: 7, file: "Hi1.webp" },
  Hi2: { frames: 58, rows: 6, file: "Hi2.webp" },
  Hi3: { frames: 94, rows: 10, file: "Hi3.webp" },
  Idle1: { frames: 97, rows: 10, file: "Idle1.webp" },
  Idle2: { frames: 150, rows: 15, file: "Idle2.webp" },
  Idle3: { frames: 259, rows: 26, file: "Idle3.webp" },
  Idle4: { frames: 214, rows: 22, file: "Idle4.webp" },
  Idle5: { frames: 229, rows: 23, file: "Idle5.webp" },
  KidDirty: { frames: 135, rows: 14, file: "KidDirty.webp" },
  KidEat: { frames: 193, rows: 20, file: "KidEat.webp" },
  KidHungry: { frames: 122, rows: 13, file: "KidHungry.webp" },
  KidStand: { frames: 101, rows: 11, file: "KidStand.webp" },
  LevelUp: { frames: 83, rows: 9, file: "LevelUp.webp" },
  ProstratePlay: { frames: 234, rows: 24, file: "ProstratePlay.webp" },
  SadPlay: { frames: 85, rows: 9, file: "SadPlay.webp" },
  Sick: { frames: 121, rows: 13, file: "Sick.webp" },
  Sleep2: { frames: 23, rows: 3, file: "Sleep2.webp" },
  Speak: { frames: 44, rows: 5, file: "Speak.webp" },
  UpsetPlay: { frames: 51, rows: 6, file: "UpsetPlay.webp" },
  Wake: { frames: 22, rows: 3, file: "Wake.webp" },
};

// loop=true 的动作一直循环；其余放一遍就回待机
export const PLAY = {
  Clean: { loop: false },
  Clean2: { loop: false },
  Cure: { loop: false },
  Eat: { loop: false },
  Eat2: { loop: false },
  EggAppear: { loop: false },
  EggStand: { loop: true },
  Enter: { loop: false },
  Exit: { loop: false },
  GGEat: { loop: false },
  GGHappy: { loop: false },
  GGIdle: { loop: true },
  Happy: { loop: false },
  Happy2: { loop: false },
  HappyHi: { loop: false },
  Hi1: { loop: false },
  Hi2: { loop: false },
  Hi3: { loop: false },
  Idle1: { loop: true },
  Idle2: { loop: true },
  Idle3: { loop: true },
  Idle4: { loop: true },
  Idle5: { loop: true },
  KidDirty: { loop: false },
  KidEat: { loop: false },
  KidHungry: { loop: false },
  KidStand: { loop: true },
  LevelUp: { loop: false },
  ProstratePlay: { loop: true },
  SadPlay: { loop: false },
  Sick: { loop: false },
  Sleep2: { loop: true },
  Speak: { loop: true },
  UpsetPlay: { loop: false },
  Wake: { loop: false },
};